//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugachBotTelegram.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KItyaSx1Cl4gZBh9+07AkarRbkttq16EfNNYgSLBGlNTYht+L9wHbzDH7EGqOCzkUNi9xqGcLZAWgIb8i" +
            "xjraFkOLpAJiJUPeM+zpqHrJUY=")]
        public string OpenweathermapAppId {
            get {
                return ((string)(this["OpenweathermapAppId"]));
            }
            set {
                this["OpenweathermapAppId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@" sLNifNtyZ0ibMd8A9jtIGY52b3sIAHF1TaD77n2ukuQHv1XOPhcaleyqLzscJBn/J3ZXAfgzxe9khUNuPmxU5z0XcydeF1Xzwq8UXg/ayQzGXwE+KNf6UEHD/oy3Mo12k7LTbM9ZFap8xjjiU3IV7mNXsZgJBVlyzZbzP4NNXq0vZ5svMc8DbHxmv0qbjVzO0d7r1UdYKEElYmSKcTc1AdIkjUsUgcTzktY7JD5Oz9LwdPXHNPN0prhtu0hYPoWegMvj5i1LdlMCGmaEWjLJQwYYJVYQqomNCYsrhDV28cwyP67KC+RAI5N7rLkeN9qB8dLIE0XWlp7jTWW6q1hz/NAaHPBuJ0m3iH/OqtYqr60=")]
        public string TelegramToken {
            get {
                return ((string)(this["TelegramToken"]));
            }
            set {
                this["TelegramToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KAeF9DHA1rFGyWgB5+mj8w==")]
        public string ProxyPassword {
            get {
                return ((string)(this["ProxyPassword"]));
            }
            set {
                this["ProxyPassword"] = value;
            }
        }
    }
}
