//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugachBotTelegram.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KItyaSx1Cl4gZBh9+07AkarRbkttq16EfNNYgSLBGlNTYht+L9wHbzDH7EGqOCzkUNi9xqGcLZAWgIb8i" +
            "xjraFkOLpAJiJUPeM+zpqHrJUY=")]
        public string OpenweathermapAppId {
            get {
                return ((string)(this["OpenweathermapAppId"]));
            }
            set {
                this["OpenweathermapAppId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ix6LTEenYBc5oMPvBTz1kYdnXdsnBVdxiyg1IsFmJvAdEPDiMvDGQPr/rtXkf4Ms1RycM9pV8Lr2WHHdr" +
            "gFAzlAZMGzRmjVaqX3kvi6k2AAkLbqeMT/AmNMNa57RG4SJ")]
        public string TelegramToken {
            get {
                return ((string)(this["TelegramToken"]));
            }
            set {
                this["TelegramToken"] = value;
            }
        }
    }
}
